blueprint:
  name: Turn off lights after no presence/motion detected for a period with optional ignore hours
  description: >
    Turn off the selected lights after no presence or motion is detected by the selected sensors for a specified duration.
    The timer resets each time motion or presence is detected. You can specify hours when the automation should ignore turning off the lights.

  domain: automation
  input:
    lights:
      name: Lights
      description: The lights to turn off
      selector:
        target:
          entity:
            domain: light
    presence_sensors:
      name: Presence/Motion Sensors
      description: The binary sensors with device class 'presence' or 'motion' to monitor
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - presence
            - motion
          multiple: true
    delay_time:
      name: Delay Time
      description: Time to wait after the last motion/presence is detected before turning off the lights
      default: '00:05:00'
      selector:
        time:
    ignore_start:
      name: Ignore Start Time
      description: The time when the automation should start ignoring turning off the lights
      selector:
        time:
      default: ""
    ignore_end:
      name: Ignore End Time
      description: The time when the automation should stop ignoring turning off the lights
      selector:
        time:
      default: ""

mode: restart

trigger:
  - platform: state
    entity_id: !input presence_sensors

condition:
  - condition: template
    value_template: >
      {% set sensors = expand(trigger.entity_id) %}
      {{ sensors | selectattr('state', 'eq', 'on') | list | length == 0 }}
  - condition: or
    conditions:
      - condition: template
        value_template: "{{ not (is_state('input_datetime.ignore_start', '') or is_state('input_datetime.ignore_end', '')) }}"
      - condition: time
        after: !input ignore_end
        before: !input ignore_start

action:
  - delay: !input delay_time
  - service: light.turn_off
    target: !input lights
